[font]
size = 17
normal = {family = "FiraCode Nerd Font Mono"}

[colors.primary]
background = "#101010"

[window]
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5

[mouse]
hide_when_typing = true
