[font]
size = 15
normal = {family = "FiraCode Nerd Font Mono"}
# to see icons install ttf-joypixels or ttf-apple-emoji for example

[colors.primary]
background = "#0c0c0c"

[window.padding]
x = 5
y = 5

[mouse]
hide_when_typing = true
